#SPDX-License-Identifier: MIT-0
---
- name: Instalar Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Iniciar Nginx manualmente
  shell: |
    service nginx start
  args:
    executable: /bin/bash
